### ISSUE TITLE
car.destroy() doesn't work correctly 

### ISSUE THREAD

**Issue by theochit** [EmceeEscher/Roy-the-Traffic-Cop#10]
In World, calling m_car.destroy() just makes the car huge, doesn't seem to release any resources.

**Comment by PenguinFlyingHigh** [comment]
Got the car to disappear after crossing the boundary. Only works with vectors, but that's fine since our lanes will be vector.

**Comment by theochit** [comment]
Nice, I'll wait until its in master to clear this

**Comment by PenguinFlyingHigh** [comment]
car is erased properly.
