### ISSUE TITLE
Error if you let the game sit for 20 seconds

### ISSUE THREAD

**Issue by JordanRoth** [EmceeEscher/Roy-the-Traffic-Cop#19]
We get a juicy error if we let the game sit for 20 seconds and allow the car to move on its own in master right now. I think it has something to do with `this->erase_first_car()` in ` Lane::turn_car()`. Might be related to to the other destroy issue already extant. If so we can close this.

**Comment by PenguinFlyingHigh** [comment]
master branch? Yeah it's likely to do with `erase_first_car(). ` I had a similar issue when I was trying to get destroy working. Ideally Nicky's branch should be able to add a fix in. We'll chat today.

**Comment by PenguinFlyingHigh** [comment]
I think the error is fixed now with destroy working properly.
