### ISSUE TITLE
Change conditional which allows cars to go

### ISSUE THREAD

**Issue by theochit** [EmceeEscher/Roy-the-Traffic-Cop#24]
Focused on other things atm, but since we only had one car before, the conditions for a car to go are pretty much just that it's velocity is 0 and it's at the front of its lane's car array. This allows players to call multiple cars rapidly if they are quick. We should just add a condition that it can only go if its velocity is 0 and it's at the stop sign

**Comment by nikrolas** [comment]
Just put in fix for this - now they have to be at stop and at 0 before going
