### ISSUE TITLE
Note for Refactoring Stage 

### ISSUE THREAD

**Issue by theochit** [EmceeEscher/Roy-the-Traffic-Cop#26]
"By the way, I added a new boolean flag that says whether cars have turned or not so that they can move after. The better solution would be to change `m_in_beyond_intersection` into an array like before so that we can have three states (in line, turning, turned). It would be a hassle because of how much we use `m_in_beyond_intersection`. Does anyone mind if i make a note of it and we do this in the refactoring part of the project if we want to?"

**Comment by nikrolas** [comment]
Refer to #27 - we can still refactor in the future however.
