### ISSUE TITLE
Cars go before they are told to

### ISSUE THREAD

**Issue by theochit** [EmceeEscher/Roy-the-Traffic-Cop#27]
So far, two cases we noticed where this happens.
1. The player tells a car to go, and then a second car spawns in that lane while the first car is turning. The second car will go immediately and not stop at the sign.

2. If a car's timer runs out, the cars behind it will stop at the stop sign, and then go without waiting to be told.

**Comment by EmceeEscher** [comment]
In the case of case 1, the arrow will usually stay white, instead of changing color to green when it reaches the stop sign.

**Comment by nikrolas** [comment]
Fixed - this was an issue because the m_beyond_intersection_ was reset to false after reaching r > 1.0. It being false is how it determined what car is in a lane queue.

The arrow remaning white after several clicks is still an issue.
