### ISSUE TITLE
Freeze/crash when AI chooses direction after auto-turn

### ISSUE THREAD

**Issue by EmceeEscher** [EmceeEscher/Roy-the-Traffic-Cop#28]
The AI will decide a new direction for a villain car when that car is in the second spot in line. This works fine if the player advances the line by pressing a key, but will break if the line advances because the front car ran out of time and turned automatically. It will either cause tons of lag, or crash on Mac (but only for the NORTH lane). Currently the code telling the AI to make that decision is commented out in the case of auto-turn cars, but we should fix it eventually.

**Comment by theochit** [comment]
@EmceeEscher does this still happen?

**Comment by PenguinFlyingHigh** [comment]
I think we fixed this.
